import type { Metadata } from "next";

import "./globals.css";
import HeroBackground from "./components/HeroBackground";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       
      ><div className="min-h-screen bg-[#EDEDE9] w-full relative  z-10 ">
        <HeroBackground  />
        <div className="   w-full mx-auto">
        <Navbar />
      <main className=" max-w-5xl mx-auto ">
{children}
      </main>
      </div>
      </div>
      
        
      </body>
    </html>
  );
}
